server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: retail_store-api

  main:
    allow-bean-definition-overriding: true
 
# ===============================================
# =  Database config
# ===============================================
  datasource:
    url: jdbc:h2:mem:STORE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS STORE;DB_CLOSE_ON_EXIT=FALSE;;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password: 123
    hibernate:
      hbm2ddl:
        auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always   
      data-locations: classpath*:data.sql
# ===============================================
# = Management config
# ===============================================
management:
  health:
    kubernetes:
     enabled : false
  info:
   kubernetes:
     enabled : false
  endpoints:
    web:
      exposure:
        include: info, health    


# ===============================================
# =  Security config
# ===============================================
jwt:
  secret: unsecured # // TODO replace with jasypt
  token:
    validity: 3600 # in seconds
    
# ===============================================
# = Swagger config
# ===============================================
store:
  swagger-ui:
    enabled: true
    title: "Retail Store REST API"
    description: " Retail Store REST API"
    version: 1.0.0
    ted:
  # ===============================================
  # = Security config
  # ===============================================
  security:
    contentSecurityPolicy:
    insecured-endpoints:
      - "/actuator/**"
      - "/internal/**"
      - "/h2-console/**"
      - "/login/**"
      
    
# ===============================================
# = General logging config
# ===============================================
logging:
  level:
    root: info
    eg.retail: debug