server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: retail_store-api

  main:
    allow-bean-definition-overriding: true
    
# ===============================================
# = Management config
# ===============================================
management:
  health:
    kubernetes:
     enabled : false
  info:
   kubernetes:
     enabled : false
  endpoints:
    web:
      exposure:
        include: info, health    

# ===============================================
# =  Database config
# ===============================================
  datasource:
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS STORE
    driverClassName: org.h2.Driver
    username: sa
    password:
    hibernate:
      hbm2ddl:
        auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect  
  sql:
    init:
      mode: always
# ===============================================
# =  Security config
# ===============================================
jwt:
  secret: unsecured # // TODO replace with jasypt
  token:
    validity: 3600 # in seconds
    
# ===============================================
# = Swagger config
# ===============================================
store:
  swagger-ui:
    enabled: true
    title: "Retail Store REST API"
    description: " Retail Store REST API"
    version: 1.0.0
    
# ===============================================
# = General logging config
# ===============================================
logging:
  level:
    root: info
    eg.retail: debug